export const militaryTimes = {
    "12:00 AM": "00:00.00",
    "12:30 AM": "00:30.00",
    "01:00 AM": "01:00.00",
    "01:30 AM": "01:30.00",
    "02:00 AM": "02:00.00",
    "02:30 AM": "02:30.00",
    "03:00 AM": "03:00.00",
    "03:30 AM": "03:30.00",
    "04:00 AM": "04:00.00",
    "04:30 AM": "04:30.00",
    "05:00 AM": "05:00.00",
    "05:30 AM": "05:30.00",
    "06:00 AM": "06:00.00",
    "06:30 AM": "06:30.00",
    "07:00 AM": "07:00.00",
    "07:30 AM": "07:30.00",
    "08:00 AM": "08:00.00",
    "08:30 AM": "08:30.00",
    "09:00 AM": "09:00.00",
    "09:30 AM": "09:30.00",
    "10:00 AM": "10:00.00",
    "10:30 AM": "10:30.00",
    "11:00 AM": "11:00.00",
    "11:30 AM": "11:30.00",
    "12:00 PM": "12:00.00",
    "12:30 PM": "12:30.00",
    "01:00 PM": "13:00.00",
    "01:30 PM": "13:30.00",
    "02:00 PM": "14:00.00",
    "02:30 PM": "14:30.00",
    "03:00 PM": "15:00.00",
    "03:30 PM": "15:30.00",
    "04:00 PM": "16:00.00",
    "04:30 PM": "16:30.00",
    "05:00 PM": "17:00.00",
    "05:30 PM": "17:30.00",
    "06:00 PM": "18:00.00",
    "06:30 PM": "18:30.00",
    "07:00 PM": "19:00.00",
    "07:30 PM": "19:30.00",
    "08:00 PM": "20:00.00",
    "08:30 PM": "20:30.00",
    "09:00 PM": "21:00.00",
    "09:30 PM": "21:30.00",
    "10:00 PM": "22:00.00",
    "10:30 PM": "22:30.00",
    "11:00 PM": "23:00.00",
    "11:30 PM": "23:30.00"
}

export const timeZones = {
    "Eastern Time - New York": "America/New_York",
    "Hawaii Time": "Pacific/Honolulu",
    "Pacific Time - Los Angeles": "America/Los_Angeles",
    "Mountain Time - Denver": "America/Denver",
    "Mountain Time - Arizona": "America/Phoenix",
    "Central Time - Chicago": "America/Chicago",
    "Atlantic - South Georgia": "Atlantic/South_Georgia",
    "Pago Pago": "Pacific/Pago_Pago",
    "Pacific Time - Tijuana": "America/Tijuana",
    "Mountain Time - Chihuahua, Mazatlan": "America/Mazatlan",
    "Central Time - Mexico City": "America/Mexico_City",
    "Central Time - Regina": "America/Regina",
    "Guatemala": "America/Guatemala",
    "Bogota": "America/Bogota",
    "Lima": "America/Lima",
    "Caracas": "America/Caracas",
    "Atlantic Time - Halifax": "America/Halifax",
    "Guyana": "America/Guyana",
    "La Paz": "America/La_Paz",
    "Buenos Aires": "America/Argentina/Buenos_Aires",
    "Godthab": "America/Godthab",
    "Montevideo": "America/Montevideo",
    "Newfoundland Time - St. Johns": "America/St_Johns",
    "Santiago": "America/Santiago",
    "Sao Paulo": "America/Sao_Paulo",
    "Azores": "Atlantic/Azores",
    "Cape Verde": "Atlantic/Cape_Verde",
    "Casablanca": "Africa/Casablanca",
    "Dublin": "Europe/Dublin",
    "Lisbon": "Europe/Lisbon",
    "London": "Europe/London",
    "Monrovia": "Africa/Monrovia",
    "Algiers": "Africa/Algiers",
    "Amsterdam": "Europe/Amsterdam",
    "Berlin": "Europe/Berlin",
    "Brussels": "Europe/Brussels",
    "Budapest": "Europe/Budapest",
    "Central European Time - Belgrade": "Europe/Belgrade",
    "Central European Time - Prague": "Europe/Prague",
    "Copenhagen": "Europe/Copenhagen",
    "Madrid": "Europe/Madrid",
    "Paris": "Europe/Paris",
    "Rome": "Europe/Rome",
    "Stockholm": "Europe/Stockholm",
    "Vienna": "Europe/Vienna",
    "Warsaw": "Europe/Warsaw",
    "Athens": "Europe/Athens",
    "Bucharest": "Europe/Bucharest",
    "Cairo": "Africa/Cairo",
    "Jerusalem": "Asia/Jerusalem",
    "Johannesburg": "Africa/Johannesburg",
    "Helsinki": "Europe/Helsinki",
    "Kiev": "Europe/Kiev",
    "Moscow-01 - Kaliningrad": "Europe/Kaliningrad",
    "Riga": "Europe/Riga",
    "Sofia": "Europe/Sofia",
    "Tallinn": "Europe/Tallinn",
    "Vilnius": "Europe/Vilnius",
    "Istanbul": "Europe/Istanbul",
    "Baghdad": "Asia/Baghdad",
    "Nairobi": "Africa/Nairobi",
    "Minsk": "Europe/Minsk",
    "Riyadh": "Asia/Riyadh",
    "Moscow+00 - Moscow": "Europe/Moscow",
    "Tehran": "Asia/Tehran",
    "Baku": "Asia/Baku",
    "Moscow+01 - Samara": "Europe/Samara",
    "Tbilisi": "Asia/Tbilisi",
    "Yerevan": "Asia/Yerevan",
    "Kabul": "Asia/Kabul",
    "Karachi": "Asia/Karachi",
    "Moscow+02 - Yekaterinburg": "Asia/Yekaterinburg",
    "Tashkent": "Asia/Tashkent",
    "Colombo": "Asia/Colombo",
    "Almaty": "Asia/Almaty",
    "Dhaka": "Asia/Dhaka",
    "Rangoon": "Asia/Rangoon",
    "Bangkok": "Asia/Bangkok",
    "Jakarta": "Asia/Jakarta",
    "Moscow+04 - Krasnoyarsk": "Asia/Krasnoyarsk",
    "China Time - Beijing": "Asia/Shanghai",
    "Hong Kong": "Asia/Hong_Kong",
    "Kuala Lumpur": "Asia/Kuala_Lumpur",
    "Moscow+05 - Irkutsk": "Asia/Irkutsk",
    "Singapore": "Asia/Singapore",
    "Taipei": "Asia/Taipei",
    "Ulaanbaatar": "Asia/Ulaanbaatar",
    "Western Time - Perth": "Australia/Perth",
    "Moscow+06 - Yakutsk": "Asia/Yakutsk",
    "Seoul": "Asia/Seoul",
    "Tokyo": "Asia/Tokyo",
    "Central Time - Darwin": "Australia/Darwin",
    "Eastern Time - Brisbane": "Australia/Brisbane",
    "Guam": "Pacific/Guam",
    "Moscow+07 - Magadan": "Asia/Magadan",
    "Moscow+07 - Yuzhno-Sakhalinsk": "Asia/Vladivostok",
    "Port Moresby": "Pacific/Port_Moresby",
    "Central Time - Adelaide": "Australia/Adelaide",
    "Eastern Time - Hobart": "Australia/Hobart",
    "Eastern Time - Melbourne, Sydney": "Australia/Sydney",
    "Guadalcanal": "Pacific/Guadalcanal",
    "Noumea": "Pacific/Noumea",
    "Majuro": "Pacific/Majuro",
    "Moscow+09 - Petropavlovsk-Kamchatskiy": "Asia/Kamchatka",
    "Auckland": "Pacific/Auckland",
    "Fakaofo": "Pacific/Fakaofo",
    "Fiji": "Pacific/Fiji",
    "Tongatapu": "Pacific/Tongatapu",
    "Apia": "Pacific/Apia"
}

export const countryCodes = {
    "United States of America": "US",
    "Afghanistan": "AF",
    "Åland Islands": "AX",
    "Albania": "AL",
    "Algeria": "DZ",
    "American Samoa": "AS",
    "Andorra": "AD",
    "Angola": "AO",
    "Anguilla": "AI",
    "Antarctica": "AQ",
    "Antigua and Barbuda": "AG",
    "Argentina": "AR",
    "Armenia": "AM",
    "Aruba": "AW",
    "Australia": "AU",
    "Austria": "AT",
    "Azerbaijan": "AZ",
    "Bahamas": "BS",
    "Bahrain": "BH",
    "Bangladesh": "BD",
    "Barbados": "BB",
    "Belarus": "BY",
    "Belgium": "BE",
    "Belize": "BZ",
    "Benin": "BJ",
    "Bermuda": "BM",
    "Bhutan": "BT",
    "Bolivia (Plurinational State of)": "BO",
    "Bonaire, Sint Eustatius and Saba": "BQ",
    "Bosnia and Herzegovina": "BA",
    "Botswana": "BW",
    "Bouvet Island": "BV",
    "Brazil": "BR",
    "British Indian Ocean Territory": "IO",
    "Brunei Darussalam": "BN",
    "Bulgaria": "BG",
    "Burkina Faso": "BF",
    "Burundi": "BI",
    "Cabo Verde": "CV",
    "Cambodia": "KH",
    "Cameroon": "CM",
    "Canada": "CA",
    "Cayman Islands": "KY",
    "Central African Republic": "CF",
    "Chad": "TD",
    "Chile": "CL",
    "China": "CN",
    "Christmas Island": "CX",
    "Cocos (Keeling) Islands": "CC",
    "Colombia": "CO",
    "Comoros": "KM",
    "Congo (Democratic Republic)": "CD",
    "Congo": "CG",
    "Cook Islands": "CK",
    "Costa Rica": "CR",
    "Croatia": "HR",
    "Cuba": "CU",
    "Curaçao": "CW",
    "Cyprus": "CY",
    "Czechia": "CZ",
    "Côte d'Ivoire": "CI",
    "Denmark": "DK",
    "Djibouti": "DJ",
    "Dominica": "DM",
    "Dominican Republic": "DO",
    "Ecuador": "EC",
    "Egypt": "EG",
    "El Salvador": "SV",
    "Equatorial Guinea": "GQ",
    "Eritrea": "ER",
    "Estonia": "EE",
    "Eswatini": "SZ",
    "Ethiopia": "ET",
    "Falkland Islands (Malvinas)": "FK",
    "Faroe Islands": "FO",
    "Fiji": "FJ",
    "Finland": "FI",
    "France": "FR",
    "French Guiana": "GF",
    "French Polynesia": "PF",
    "French Southern Territories": "TF",
    "Gabon": "GA",
    "Gambia": "GM",
    "Georgia": "GE",
    "Germany": "DE",
    "Ghana": "GH",
    "Gibraltar": "GI",
    "Greece": "GR",
    "Greenland": "GL",
    "Grenada": "GD",
    "Guadeloupe": "GP",
    "Guam": "GU",
    "Guatemala": "GT",
    "Guernsey": "GG",
    "Guinea": "GN",
    "Guinea-Bissau": "GW",
    "Guyana": "GY",
    "Haiti": "HT",
    "Heard Island and McDonald Islands": "HM",
    "Holy See": "VA",
    "Honduras": "HN",
    "Hong Kong": "HK",
    "Hungary": "HU",
    "Iceland": "IS",
    "India": "IN",
    "Indonesia": "ID",
    "Iran (Islamic Republic)": "IR",
    "Iraq": "IQ",
    "Ireland": "IE",
    "Isle of Man": "IM",
    "Israel": "IL",
    "Italy": "IT",
    "Jamaica": "JM",
    "Japan": "JP",
    "Jersey": "JE",
    "Jordan": "JO",
    "Kazakhstan": "KZ",
    "Kenya": "KE",
    "Kiribati": "KI",
    "Korea (Democratic People's Republic)": "KP",
    "Korea (Republic)": "KR",
    "Kuwait": "KW",
    "Kyrgyzstan": "KG",
    "Lao People's Democratic Republic": "LA",
    "Latvia": "LV",
    "Lebanon": "LB",
    "Lesotho": "LS",
    "Liberia": "LR",
    "Libya": "LY",
    "Liechtenstein": "LI",
    "Lithuania": "LT",
    "Luxembourg": "LU",
    "Macao": "MO",
    "Madagascar": "MG",
    "Malawi": "MW",
    "Malaysia": "MY",
    "Maldives": "MV",
    "Mali": "ML",
    "Malta": "MT",
    "Marshall Islands": "MH",
    "Martinique": "MQ",
    "Mauritania": "MR",
    "Mauritius": "MU",
    "Mayotte": "YT",
    "Mexico": "MX",
    "Micronesia (Federated States)": "FM",
    "Moldova (Republic)": "MD",
    "Monaco": "MC",
    "Mongolia": "MN",
    "Montenegro": "ME",
    "Montserrat": "MS",
    "Morocco": "MA",
    "Mozambique": "MZ",
    "Myanmar": "MM",
    "Namibia": "NA",
    "Nauru": "NR",
    "Nepal": "NP",
    "Netherlands": "NL",
    "New Caledonia": "NC",
    "New Zealand": "NZ",
    "Nicaragua": "NI",
    "Niger": "NE",
    "Nigeria": "NG",
    "Niue": "NU",
    "Norfolk Island": "NF",
    "Northern Mariana Islands": "MP",
    "Norway": "NO",
    "Oman": "OM",
    "Pakistan": "PK",
    "Palau": "PW",
    "Palestine (State)": "PS",
    "Panama": "PA",
    "Papua New Guinea": "PG",
    "Paraguay": "PY",
    "Peru": "PE",
    "Philippines": "PH",
    "Pitcairn": "PN",
    "Poland": "PL",
    "Portugal": "PT",
    "Puerto Rico": "PR",
    "Qatar": "QA",
    "Republic of North Macedonia": "MK",
    "Romania": "RO",
    "Russian Federation": "RU",
    "Rwanda": "RW",
    "Réunion": "RE",
    "Saint Barthélemy": "BL",
    "Saint Helena, Ascension and Tristan da Cunha": "SH",
    "Saint Kitts and Nevis": "KN",
    "Saint Lucia": "LC",
    "Saint Martin (French part)": "MF",
    "Saint Pierre and Miquelon": "PM",
    "Saint Vincent and the Grenadines": "VC",
    "Samoa": "WS",
    "San Marino": "SM",
    "Sao Tome and Principe": "ST",
    "Saudi Arabia": "SA",
    "Senegal": "SN",
    "Serbia": "RS",
    "Seychelles": "SC",
    "Sierra Leone": "SL",
    "Singapore": "SG",
    "Sint Maarten (Dutch part)": "SX",
    "Slovakia": "SK",
    "Slovenia": "SI",
    "Solomon Islands": "SB",
    "Somalia": "SO",
    "South Africa": "ZA",
    "South Georgia and the South Sandwich Islands": "GS",
    "South Sudan": "SS",
    "Spain": "ES",
    "Sri Lanka": "LK",
    "Sudan": "SD",
    "Suriname": "SR",
    "Svalbard and Jan Mayen": "SJ",
    "Sweden": "SE",
    "Switzerland": "CH",
    "Syrian Arab Republic": "SY",
    "Taiwan (Province of China)": "TW",
    "Tajikistan": "TJ",
    "Tanzania, United Republic of": "TZ",
    "Thailand": "TH",
    "Timor-Leste": "TL",
    "Togo": "TG",
    "Tokelau": "TK",
    "Tonga": "TO",
    "Trinidad and Tobago": "TT",
    "Tunisia": "TN",
    "Turkey": "TR",
    "Turkmenistan": "TM",
    "Turks and Caicos Islands": "TC",
    "Tuvalu": "TV",
    "Uganda": "UG",
    "Ukraine": "UA",
    "United Arab Emirates": "AE",
    "United Kingdom (Great Britain / Northern Ireland)": "GB",
    "United States Minor Outlying Islands": "UM",
    "Uruguay": "UY",
    "Uzbekistan": "UZ",
    "Vanuatu": "VU",
    "Venezuela (Bolivarian Republic)": "VE",
    "Viet Nam": "VN",
    "Virgin Islands (British)": "VG",
    "Virgin Islands (U.S.)": "VI",
    "Wallis and Futuna": "WF",
    "Western Sahara": "EH",
    "Yemen": "YE",
    "Zambia": "ZM",
    "Zimbabwe": "ZW",
    "Åland Islands": "AX"
}

export const eventCategories = {
    //"Choose an event category": "",
    "Music": "music",
    "Sports": "sports",
    "Arts & Theatre": "artTheater",
    "Food & Drink": "foodDrink",
    "Charity & Causes": "charityCauses",
    "Family": "family",
    "Meeting": "meeting",
    "Other": "other",
}

export const americasCurrencies = {
    "United States Dollar (USD) $": "USD $",
    "Canada Dollar (CAD) $": "CAD $",
    "Mexico Peso (MXN) $": "MXN $"
}

export const europeCurrencies = {
    "Euro Member Countries (EUR) €": "EUR €",
    "United Kingdom Pound (GBP) £": "GBP £",
    "Czech Republic Koruna (CZK) Kc": "CZK Kc",
    "Denmark Krone (DKK) kr": "DKK kr",
    "Hungary Forint (HUF) Ft": "HUF Ft",
    "Norway Krone (NOK) kr": "NOK kr",
    "Poland Zloty (PLN) zl": "PLN zl",
    "Sweden Krona (SEK) kr": "SEK kr",
    "Switzerland Franc (CHF) CHF": "CHF"
}

export const asiaCurrencies = {
    "Japan Yen (JPY) ¥": "JPY ¥",
    "Australia Dollar (AUD) $": "AUD $",
    "New Zealand Dollar (NZD) $": "NZD $",
    "Hong Kong Dollar (HKD) $": "HKD $",
    "Singapore Dollar (SGD) $": "SGD $",
    "Israel Shekel (ILS) ₪": "ILS ₪",
    "Philippines Peso (PHP) ₱": "PHP ₱",
    "Taiwan New Dollar (TWD) NT$": "TWD NT$",
    "Thailand Baht (THB) ฿": "THB ฿",
    "Russia Ruble (RUB) ₽": "RUB ₽",
}