export const dayTimes = [
    "12:00 AM",
    "12:30 AM",
    "01:00 AM",
    "01:30 AM",
    "02:00 AM",
    "02:30 AM",
    "03:00 AM",
    "03:30 AM",
    "04:00 AM",
    "04:30 AM",
    "05:00 AM",
    "05:30 AM",
    "06:00 AM",
    "06:30 AM",
    "07:00 AM",
    "07:30 AM",
    "08:00 AM",
    "08:30 AM",
    "09:00 AM",
    "09:30 AM",
    "10:00 AM",
    "10:30 AM",
    "11:00 AM",
    "11:30 AM",
    "12:00 PM",
    "12:30 PM",
    "01:00 PM",
    "01:30 PM",
    "02:00 PM",
    "02:30 PM",
    "03:00 PM",
    "03:30 PM",
    "04:00 PM",
    "04:30 PM",
    "05:00 PM",
    "05:30 PM",
    "06:00 PM",
    "06:30 PM",
    "07:00 PM",
    "07:30 PM",
    "08:00 PM",
    "08:30 PM",
    "09:00 PM",
    "09:30 PM",
    "10:00 PM",
    "10:30 PM",
    "11:00 PM",
    "11:30 PM"
]

export const timeMilliseconds = {
    "12:00 AM": "0",
    "12:30 AM": "1800000",
    "01:00 AM": "3600000",
    "01:30 AM": "5400000",
    "02:00 AM": "7200000",
    "02:30 AM": "9000000",
    "03:00 AM": "10800000",
    "03:30 AM": "12600000",
    "04:00 AM": "14400000",
    "04:30 AM": "16200000",
    "05:00 AM": "18000000",
    "05:30 AM": "19800000",
    "06:00 AM": "21600000",
    "06:30 AM": "23400000",
    "07:00 AM": "25200000",
    "07:30 AM": "27000000",
    "08:00 AM": "28800000",
    "08:30 AM": "30600000",
    "09:00 AM": "32400000",
    "09:30 AM": "34200000",
    "10:00 AM": "36000000",
    "10:30 AM": "37800000",
    "11:00 AM": "39600000",
    "11:30 AM": "41400000",
    "12:00 PM": "43200000",
    "12:30 PM": "45000000",
    "01:00 PM": "46800000",
    "01:30 PM": "48600000",
    "02:00 PM": "50400000",
    "02:30 PM": "52200000",
    "03:00 PM": "54000000",
    "03:30 PM": "55800000",
    "04:00 PM": "57600000",
    "04:30 PM": "59400000",
    "05:00 PM": "61200000",
    "05:30 PM": "63000000",
    "06:00 PM": "64800000",
    "06:30 PM": "66600000",
    "07:00 PM": "68400000",
    "07:30 PM": "70200000",
    "08:00 PM": "72000000",
    "08:30 PM": "73800000",
    "09:00 PM": "75600000",
    "09:30 PM": "77400000",
    "10:00 PM": "79200000",
    "10:30 PM": "81000000",
    "11:00 PM": "82800000",
    "11:30 PM": "84600000"
}

export const timeZones = {
    "Eastern Time - New York": "America/New_York",
    "Hawaii Time": "Pacific/Honolulu",
    "Pacific Time - Los Angeles": "America/Los_Angeles",
    "Mountain Time - Denver": "America/Denver",
    "Mountain Time - Arizona": "America/Phoenix",
    "Central Time - Chicago": "America/Chicago",
    "Atlantic - South Georgia": "Atlantic/South_Georgia",
    "Pago Pago": "Pacific/Pago_Pago",
    "Pacific Time - Tijuana": "America/Tijuana",
    "Mountain Time - Chihuahua, Mazatlan": "America/Mazatlan",
    "Central Time - Mexico City": "America/Mexico_City",
    "Central Time - Regina": "America/Regina",
    "Guatemala": "America/Guatemala",
    "Bogota": "America/Bogota",
    "Lima": "America/Lima",
    "Caracas": "America/Caracas",
    "Atlantic Time - Halifax": "America/Halifax",
    "Guyana": "America/Guyana",
    "La Paz": "America/La_Paz",
    "Buenos Aires": "America/Argentina/Buenos_Aires",
    "Godthab": "America/Godthab",
    "Montevideo": "America/Montevideo",
    "Newfoundland Time - St. Johns": "America/St_Johns",
    "Santiago": "America/Santiago",
    "Sao Paulo": "America/Sao_Paulo",
    "Azores": "Atlantic/Azores",
    "Cape Verde": "Atlantic/Cape_Verde",
    "Casablanca": "Africa/Casablanca",
    "Dublin": "Europe/Dublin",
    "Lisbon": "Europe/Lisbon",
    "London": "Europe/London",
    "Monrovia": "Africa/Monrovia",
    "Algiers": "Africa/Algiers",
    "Amsterdam": "Europe/Amsterdam",
    "Berlin": "Europe/Berlin",
    "Brussels": "Europe/Brussels",
    "Budapest": "Europe/Budapest",
    "Central European Time - Belgrade": "Europe/Belgrade",
    "Central European Time - Prague": "Europe/Prague",
    "Copenhagen": "Europe/Copenhagen",
    "Madrid": "Europe/Madrid",
    "Paris": "Europe/Paris",
    "Rome": "Europe/Rome",
    "Stockholm": "Europe/Stockholm",
    "Vienna": "Europe/Vienna",
    "Warsaw": "Europe/Warsaw",
    "Athens": "Europe/Athens",
    "Bucharest": "Europe/Bucharest",
    "Cairo": "Africa/Cairo",
    "Jerusalem": "Asia/Jerusalem",
    "Johannesburg": "Africa/Johannesburg",
    "Helsinki": "Europe/Helsinki",
    "Kiev": "Europe/Kiev",
    "Moscow-01 - Kaliningrad": "Europe/Kaliningrad",
    "Riga": "Europe/Riga",
    "Sofia": "Europe/Sofia",
    "Tallinn": "Europe/Tallinn",
    "Vilnius": "Europe/Vilnius",
    "Istanbul": "Europe/Istanbul",
    "Baghdad": "Asia/Baghdad",
    "Nairobi": "Africa/Nairobi",
    "Minsk": "Europe/Minsk",
    "Riyadh": "Asia/Riyadh",
    "Moscow+00 - Moscow": "Europe/Moscow",
    "Tehran": "Asia/Tehran",
    "Baku": "Asia/Baku",
    "Moscow+01 - Samara": "Europe/Samara",
    "Tbilisi": "Asia/Tbilisi",
    "Yerevan": "Asia/Yerevan",
    "Kabul": "Asia/Kabul",
    "Karachi": "Asia/Karachi",
    "Moscow+02 - Yekaterinburg": "Asia/Yekaterinburg",
    "Tashkent": "Asia/Tashkent",
    "Colombo": "Asia/Colombo",
    "Almaty": "Asia/Almaty",
    "Dhaka": "Asia/Dhaka",
    "Rangoon": "Asia/Rangoon",
    "Bangkok": "Asia/Bangkok",
    "Jakarta": "Asia/Jakarta",
    "Moscow+04 - Krasnoyarsk": "Asia/Krasnoyarsk",
    "China Time - Beijing": "Asia/Shanghai",
    "Hong Kong": "Asia/Hong_Kong",
    "Kuala Lumpur": "Asia/Kuala_Lumpur",
    "Moscow+05 - Irkutsk": "Asia/Irkutsk",
    "Singapore": "Asia/Singapore",
    "Taipei": "Asia/Taipei",
    "Ulaanbaatar": "Asia/Ulaanbaatar",
    "Western Time - Perth": "Australia/Perth",
    "Moscow+06 - Yakutsk": "Asia/Yakutsk",
    "Seoul": "Asia/Seoul",
    "Tokyo": "Asia/Tokyo",
    "Central Time - Darwin": "Australia/Darwin",
    "Eastern Time - Brisbane": "Australia/Brisbane",
    "Guam": "Pacific/Guam",
    "Moscow+07 - Magadan": "Asia/Magadan",
    "Moscow+07 - Yuzhno-Sakhalinsk": "Asia/Vladivostok",
    "Port Moresby": "Pacific/Port_Moresby",
    "Central Time - Adelaide": "Australia/Adelaide",
    "Eastern Time - Hobart": "Australia/Hobart",
    "Eastern Time - Melbourne, Sydney": "Australia/Sydney",
    "Guadalcanal": "Pacific/Guadalcanal",
    "Noumea": "Pacific/Noumea",
    "Majuro": "Pacific/Majuro",
    "Moscow+09 - Petropavlovsk-Kamchatskiy": "Asia/Kamchatka",
    "Auckland": "Pacific/Auckland",
    "Fakaofo": "Pacific/Fakaofo",
    "Fiji": "Pacific/Fiji",
    "Tongatapu": "Pacific/Tongatapu",
    "Apia": "Pacific/Apia"
}

export const countries = [
    "United States of America",
    "Afghanistan",
    "Albania",
    "Algeria",
    "Andorra",
    "Angola",
    "Antigua and Barbuda",
    "Argentina",
    "Armenia",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahamas",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belgium",
    "Belize",
    "Benin",
    "Bhutan",
    "Bolivia",
    "Bosnia and Herzegovina",
    "Botswana",
    "Brazil",
    "Brunei",
    "Bulgaria",
    "Burkina Faso",
    "Burundi",
    "Côte d'Ivoire",
    "Cabo Verde",
    "Cambodia",
    "Cameroon",
    "Canada",
    "Central African Republic",
    "Chad",
    "Chile",
    "China",
    "Colombia",
    "Comoros",
    "Congo (Congo-Brazzaville)",
    "Costa Rica",
    "Croatia",
    "Cuba",
    "Cyprus",
    "Czechia (Czech Republic)",
    "Democratic Republic of the Congo",
    "Denmark",
    "Djibouti",
    "Dominica",
    "Dominican Republic",
    "Ecuador",
    "Egypt",
    "El Salvador",
    "Equatorial Guinea",
    "Eritrea",
    "Estonia",
    "Eswatini",
    "Ethiopia",
    "Fiji",
    "Finland",
    "France",
    "Gabon",
    "Gambia",
    "Georgia",
    "Germany",
    "Ghana",
    "Greece",
    "Grenada",
    "Guatemala",
    "Guinea",
    "Guinea-Bissau",
    "Guyana",
    "Haiti",
    "Holy See",
    "Honduras",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Iran",
    "Iraq",
    "Ireland",
    "Israel",
    "Italy",
    "Jamaica",
    "Japan",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Kiribati",
    "Kuwait",
    "Kyrgyzstan",
    "Laos",
    "Latvia",
    "Lebanon",
    "Lesotho",
    "Liberia",
    "Libya",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malta",
    "Marshall Islands",
    "Mauritania",
    "Mauritius",
    "Mexico",
    "Micronesia",
    "Moldova",
    "Monaco",
    "Mongolia",
    "Montenegro",
    "Morocco",
    "Mozambique",
    "Myanmar",
    "Namibia",
    "Nauru",
    "Nepal",
    "Netherlands",
    "New Zealand",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "North Korea",
    "North Macedonia",
    "Norway",
    "Oman",
    "Pakistan",
    "Palau",
    "Palestine State",
    "Panama",
    "Papua New Guinea",
    "Paraguay",
    "Peru",
    "Philippines",
    "Poland",
    "Portugal",
    "Qatar",
    "Romania",
    "Russia",
    "Rwanda",
    "Saint Kitts and Nevis",
    "Saint Lucia",
    "Saint Vincent and the Grenadines",
    "Samoa",
    "San Marino",
    "Sao Tome and Principe",
    "Saudi Arabia",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Sierra Leone",
    "Singapore",
    "Slovakia",
    "Slovenia",
    "Solomon Islands",
    "Somalia",
    "South Africa",
    "South Korea",
    "South Sudan",
    "Spain",
    "Sri Lanka",
    "Sudan",
    "Suriname",
    "Sweden",
    "Switzerland",
    "Syria",
    "Tajikistan",
    "Tanzania",
    "Thailand",
    "Timor-Leste",
    "Togo",
    "Tonga",
    "Trinidad and Tobago",
    "Tunisia",
    "Turkey",
    "Turkmenistan",
    "Tuvalu",
    "Uganda",
    "Ukraine",
    "United Arab Emirates",
    "United Kingdom",
    "Uruguay",
    "Uzbekistan",
    "Vanuatu",
    "Venezuela",
    "Vietnam",
    "Yemen",
    "Zambia",
    "Zimbabwe"    
]

export const currencies = {
    "Americas": null,
    "United States Dollar (USD) $": "US$",
    "Canada Dollar (CAD) $": "CA$",
    "Mexico Peso (MXN) $": "MX$",
    "Europe": null,
    "Euro Member Countries (EUR) €": "€",
    "United Kingdom Pound (GBP) £": "£",
    "Czech Republic Koruna (CZK) Kc": "Kc",
    "Denmark Krone (DKK) kr": "kr",
    "Hungary Forint (HUF) Ft": "Ft",
    "Norway Krone (NOK) kr": "kr",
    "Poland Zloty (PLN) zl": "zl",
    "Sweden Krona (SEK) kr": "kr",
    "Switzerland Franc (CHF) CHF": "CHF",
    "Asia": null,
    "Japan Yen (JPY) ¥": "¥",
    "Australia Dollar (AUD) $": "$",
    "New Zealand Dollar (NZD) $": "$",
    "Hong Kong Dollar (HKD) $": "$",
    "Singapore Dollar (SGD) $": "$",
    "Israel Shekel (ILS) ₪": "₪",
    "Philippines Peso (PHP) ₱": "₱",
    "Taiwan New Dollar (TWD) NT$": "NT$",
    "Thailand Baht (THB) ฿": "฿",
    "Russia Ruble (RUB) ₽": "₽",
}

export const currencies2 = {
    "United States Dollar (USD) $": "US$",
    "Canada Dollar (CAD) $": "CA$",
    "Mexico Peso (MXN) $": "MX$",
    "Euro Member Countries (EUR) €": "€",
    "United Kingdom Pound (GBP) £": "£",
    "Czech Republic Koruna (CZK) Kc": "Kc",
    "Denmark Krone (DKK) kr": "kr",
    "Hungary Forint (HUF) Ft": "Ft",
    "Norway Krone (NOK) kr": "kr",
    "Poland Zloty (PLN) zl": "zl",
    "Sweden Krona (SEK) kr": "kr",
    "Switzerland Franc (CHF) CHF": "CHF",
    "Japan Yen (JPY) ¥": "¥",
    "Australia Dollar (AUD) $": "$",
    "New Zealand Dollar (NZD) $": "$",
    "Hong Kong Dollar (HKD) $": "$",
    "Singapore Dollar (SGD) $": "$",
    "Israel Shekel (ILS) ₪": "₪",
    "Philippines Peso (PHP) ₱": "₱",
    "Taiwan New Dollar (TWD) NT$": "NT$",
    "Thailand Baht (THB) ฿": "฿",
    "Russia Ruble (RUB) ₽": "₽",
}

export const americasCurrencies = {
    "United States Dollar (USD) $": "US$",
    "Canada Dollar (CAD) $": "CA$",
    "Mexico Peso (MXN) $": "MX$"
}

export const europeCurrencies = {
    "Euro Member Countries (EUR) €": "€",
    "United Kingdom Pound (GBP) £": "£",
    "Czech Republic Koruna (CZK) Kc": "Kc",
    "Denmark Krone (DKK) kr": "kr",
    "Hungary Forint (HUF) Ft": "Ft",
    "Norway Krone (NOK) kr": "kr",
    "Poland Zloty (PLN) zl": "zl",
    "Sweden Krona (SEK) kr": "kr",
    "Switzerland Franc (CHF) CHF": "CHF"
}

export const asiaCurrencies = {
    "Japan Yen (JPY) ¥": "¥",
    "Australia Dollar (AUD) $": "$",
    "New Zealand Dollar (NZD) $": "$",
    "Hong Kong Dollar (HKD) $": "$",
    "Singapore Dollar (SGD) $": "$",
    "Israel Shekel (ILS) ₪": "₪",
    "Philippines Peso (PHP) ₱": "₱",
    "Taiwan New Dollar (TWD) NT$": "NT$",
    "Thailand Baht (THB) ฿": "฿",
    "Russia Ruble (RUB) ₽": "₽",
}