
/*
const eventTixOrig = {
  // sample data
  _id: "5e8199fdfc33db465d140c4b",
  isDraft: false,
  isVisible: false,
  ticket: [],
  repeat: "None",
  eventStatus: "EventScheduled",
  eventTitle: "RikaRikaStudio オンライン英語家庭教師",
  onlineInfo: "Podcast link",
  eventType: "liveOnline",
  eventCategory: "sports",
  startDateTime: "2020-06-23T23:00:00.000Z",
  endDateTime: "2020-06-25T19:30:00.000Z",
  timeZone: "America/Halifax",
  longDescription: "<p>Rika's</p><p>Event</p>↵<p>Added text</p>",
  shortDescription:
    "AmeRikaEigo\nNYデザイナーが皆様の英語学習をお手伝いいたします！",
  createUserId: "5da53eba74a2f98516d9b62c",
  eventNum: 75959989768,
  vanityLink: "rikarikastudio-",
  accountId: "5e600072110cbc31b17fa33c",
  createdAt: "2020-03-30T07:04:29.683Z",
  updatedAt: "2020-04-15T01:52:49.339Z",
  locationVenueName: "Nagano Stadium",
  locationNote: "take your shoes off",
  locationAddress1: "111 Blossom Road",
  locationAddress2: "4th Floor",
  locationCity: "Nagano",
  locationState: "Chūbu‎",
  locationCountryCode: "Japan",
  locationZipPostalCode: "903338",
  facebookLink: "my event f",
  twitterLink: "my event t",
  linkedinLink: "my event l",
  instagramLink: "my event i",
  refundPolicy: "7days",
  __v: 0,
  tickets: [
    {
      eventId: "5e8199fdfc33db465d140c4b",
      ticketType: { type: "String", enum: ["Free", "Paid", "Donation"] },
      freeTicket: { type: "Boolean" },
      usePriceFunction: true,
      priceFunction: {
        form: "twofer",
        args: {
          buy: 2,
          for: 15,
        },
      },
      ticketName: "初回コンサルテーション",
      currency: "USD",
      language: "JPN",
      ticketDescription:
        "レッスンを始める前の１５分間のコンサルテーションです。ゴールの設定やクラスの進め方、又、ご自身のレベルが分からなかったり、ご質問がある場合にもお気軽にご相談ください。",
      showTicketDescOnEventPage: { type: "Boolean" },
      minTicketsAllowedPerOrder: 1,
      maxTicketsAllowedPerOrder: 10,
      initialTicketPrice: 0,
      currentTicketPrice: 0,
      initialQuantity: 20000,
      remainingQuantity: 19991,
      sort: 0,
      startVisibilityDateTime: { type: "Date" },
      endVisibilityDateTime: { type: "Date" },
      startSaleDateTime: { type: "Date" },
      endSaleDateTime: { type: "Date" },
      smartContractAddress: { type: "String" },
      isZombie: { type: "Boolean" },
      _id: "5e819c06fc33db465d140c4c",
      updatedAt: "2020-03-31T22:57:27.610Z",
      createdAt: "2020-03-30T07:13:10.901Z",
      __v: 0,
    },
    {
      eventId: "5e8199fdfc33db465d140c4b",
      ticketType: { type: "String", enum: ["Free", "Paid", "Donation"] },
      freeTicket: { type: "Boolean" },
      usePriceFunction: true,
      priceFunction: {
        form: "bogo",
        args: {
          buy: 2,
          get: 1,
        },
      },
      ticketName: "オンラインプライベート英語レッスン",
      currency: "JPY",
      language: "JPN",
      ticketDescription:
        "オンライン30分プライベートコースです。イキイキと楽しみながら、自信を持って技術やテクニックをレベルアップしていただけるプライベートレッスンです。一回づつお気軽にも、お得なパッケージ料金もございます",
      showTicketDescOnEventPage: { type: "Boolean" },
      initialTicketPrice: 2000,
      currentTicketPrice: 2000,
      initialQuantity: 20000,
      remainingQuantity: 19978,
      sort: 1,
      startVisibilityDateTime: { type: "Date" },
      endVisibilityDateTime: { type: "Date" },
      startSaleDateTime: { type: "Date" },
      endSaleDateTime: { type: "Date" },
      smartContractAddress: { type: "String" },
      isZombie: { type: "Boolean" },
      _id: "5e819c8c43c286568ea23d85",
      updatedAt: "2020-03-31T22:57:27.616Z",
      createdAt: "2020-03-30T07:15:24.734Z",
      __v: 0,
    },
    {
      eventId: "5e8199fdfc33db465d140c4b",
      ticketType: { type: "String", enum: ["Free", "Paid", "Donation"] },
      freeTicket: { type: "Boolean" },
      usePriceFunction: true,
      priceFunction: {
        form: "bogo",
        args: {
          buy: 5,
          get: 2,
          discount: 0.9,
        },
      },
      ticketName: "ウィークリーエヴリディ",
      currency: "USD",
      language: "JPN",
      ticketDescription:
        "１週間毎日受講いただけるお得なプランです。１週間有効 英語３０分プライベートレッスンオンライン。１日１レッスンまでとします。",
      showTicketDescOnEventPage: { type: "Boolean" },
      maxTicketsAllowedPerOrder: 5,
      initialTicketPrice: 7200,
      currentTicketPrice: 7200,
      initialQuantity: 20000,
      remainingQuantity: 19994,
      sort: 3,
      startVisibilityDateTime: { type: "Date" },
      endVisibilityDateTime: { type: "Date" },
      startSaleDateTime: { type: "Date" },
      endSaleDateTime: { type: "Date" },
      smartContractAddress: { type: "String" },
      isZombie: { type: "Boolean" },
      _id: "5e819cbf43c286568ea23d86",
      updatedAt: "2020-03-31T19:25:00.309Z",
      createdAt: "2020-03-30T07:16:15.583Z",
      __v: 0,
    },
    {
      eventId: "5e8199fdfc33db465d140c4b",
      ticketType: { type: "String", enum: ["Free", "Paid", "Donation"] },
      freeTicket: { type: "Boolean" },
      usePriceFunction: false,
      priceFunction: {
        form: "promo",
        args: {
          promocodes: [
            {
              name: "flyers",
              amount: 0,
            },
            {
              name: "eagles",
              amount: 10,
            },
          ],
        },
      },
      ticketName: "マンスリー10回",
      currency: "JPY",
      language: "JPN",
      ticketDescription:
        "３０日間有効の合計１０回のプランです。Valid for one month Select • 英語３０分プライベートレッ",
      showTicketDescOnEventPage: { type: "Boolean" },
      minTicketsAllowedPerOrder: 2,
      initialTicketPrice: 18000,
      currentTicketPrice: 18000,
      initialQuantity: 200,
      remainingQuantity: 196,
      sort: 4,
      startVisibilityDateTime: { type: "Date" },
      endVisibilityDateTime: { type: "Date" },
      startSaleDateTime: { type: "Date" },
      endSaleDateTime: { type: "Date" },
      smartContractAddress: { type: "String" },
      isZombie: { type: "Boolean" },
      _id: "5e819cec43c286568ea23d87",
      updatedAt: "2020-03-31T19:25:00.312Z",
      createdAt: "2020-03-30T07:17:00.628Z",
      __v: 0,
    },
  ],
};
*/