export const API = process.env.REACT_APP_API_URL;
export const HOST = process.env.REACT_APP_HOST_URL;
export const PAYPAL_USE_SANDBOX =
  process.env.REACT_APP_PAYPAL_USE_SANDBOX === "true" ? true : false;
export const SUBSCRIPTION_PROMO_CODE_1 =
  process.env.REACT_APP_SUBSCRIPTION_PROMO_CODE_1;
export const SUBSCRIPTION_PROMO_CODE_2 =
  process.env.REACT_APP_SUBSCRIPTION_PROMO_CODE_2;
export const SUBSCRIPTION_PROMO_CODE_3 =
  process.env.REACT_APP_SUBSCRIPTION_PROMO_CODE_3;
export const SUBSCRIPTION_PROMO_CODE_4 =
  process.env.REACT_APP_SUBSCRIPTION_PROMO_CODE_4;
export const SUBSCRIPTION_PROMO_CODE_5 =
  process.env.REACT_APP_SUBSCRIPTION_PROMO_CODE_5;
export const SUBSCRIPTION_PROMO_CODE_6 =
  process.env.REACT_APP_SUBSCRIPTION_PROMO_CODE_6;
export const SUBSCRIPTION_PROMO_CODE_7 =
  process.env.REACT_APP_SUBSCRIPTION_PROMO_CODE_7;
export const SUBSCRIPTION_PROMO_CODE_8 =
  process.env.REACT_APP_SUBSCRIPTION_PROMO_CODE_8;
export const OSD_SUBSCRIPTION_PAYPAL_CLIENT_ID =
  process.env.REACT_APP_OSD_SUBSCRIPTION_PAYPAL_CLIENT_ID;
export const OSD_STRIPE_ACCOUNT_ID =
  process.env.REACT_APP_OSD_STRIPE_ACCOUNT_ID;
export const STRIPE_SUCCESS_URL = process.env.REACT_APP_STRIPE_SUCCESS_URL;
export const GOOGLE_CLIENT_ID = process.env.REACT_APP_GOOGLE_CLIENT_ID;
export const FACEBOOK_APP_ID = process.env.REACT_APP_FACEBOOK_APP_ID;
