export const API = process.env.REACT_APP_API_URL;
export const PAYPAL_USE_SANDBOX =
  process.env.REACT_APP_PAYPAL_USE_SANDBOX === "true" ? true : false;
export const SUBSCRIPTION_PROMO_CODE_1 =
  process.env.REACT_APP_SUBSCRIPTION_PROMO_CODE_1;
export const SUBSCRIPTION_PROMO_CODE_2 =
  process.env.REACT_APP_SUBSCRIPTION_PROMO_CODE_2;
export const OSD_SUBSCRIPTION_PAYPAL_CLIENT_ID =
  process.env.REACT_APP_OSD_SUBSCRIPTION_PAYPAL_CLIENT_ID;
